In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("HeartDisease.csv")

In [3]:
df

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0     63       1           3       145         233                    1   
1     37       1           2       130         250                    0   
2     41       0           1       130         204                    0   
3     56       1           1       120         236                    0   
4     57       0           0       120         354                    0   
..   ...     ...         ...       ...         ...                  ...   
298   57       0           0       140         241                    0   
299   45       1           3       110         264                    0   
300   68       1           0       144         193                    1   
301   57       1           0       130         131                    0   
302   57       0           1       130         236                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0           0      150            0       2.3      0   0            1       1  
1           1      187            0       3.5      0   0            2       1  
2           0      172            0       1.4      2   0            2       1  
3           1      178            0       0.8      2   0            2       1  
4           1      163            1       0.6      2   0            2       1  
..        ...      ...          ...       ...    ...  ..          ...     ...  
298         1      123            1       0.2      1   0            3       0  
299         1      132            0       1.2      1   0            3       0  
300         1      141            0       3.4      1   2            3       0  
301         1      115            1       1.2      1   1            3       0  
302         0      174            0       0.0      1   1            2       0  

[303 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   gender               303 non-null    int64  
 2   chest_pain           303 non-null    int64  
 3   rest_bps             303 non-null    int64  
 4   cholestrol           303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   rest_ecg             303 non-null    int64  
 7   thalach              303 non-null    int64  
 8   exer_angina          303 non-null    int64  
 9   old_peak             303 non-null    float64
 10  slope                303 non-null    int64  
 11  ca                   303 non-null    int64  
 12  thalassemia          303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
x=df.drop("target",axis=1)
y=df["target"]

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [9]:
x_train

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
34    51       1           3       125         213                    0   
185   44       1           0       112         290                    0   
187   54       1           0       124         266                    0   
147   60       0           3       150         240                    0   
202   58       1           0       150         270                    0   
..   ...     ...         ...       ...         ...                  ...   
203   68       1           2       180         274                    1   
255   45       1           0       142         309                    0   
72    29       1           1       130         204                    0   
235   51       1           0       140         299                    0   
37    54       1           2       150         232                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  
34          0      125            1       1.4      2   1            2  
185         0      153            0       0.0      2   1            2  
187         0      109            1       2.2      1   1            3  
147         1      171            0       0.9      2   0            2  
202         0      111            1       0.8      2   0            3  
..        ...      ...          ...       ...    ...  ..          ...  
203         0      150            1       1.6      1   0            3  
255         0      147            1       0.0      1   3            3  
72          0      202            0       0.0      2   0            2  
235         1      173            1       1.6      2   0            3  
37          0      165            0       1.6      2   0            3  

[212 rows x 13 columns]

In [10]:
x_test

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
204   62       0           0       160         164                    0   
159   56       1           1       130         221                    0   
219   48       1           0       130         256                    1   
174   60       1           0       130         206                    0   
184   50       1           0       150         243                    0   
..   ...     ...         ...       ...         ...                  ...   
106   69       1           3       160         234                    1   
105   68       0           2       120         211                    0   
67    45       0           1       130         234                    0   
291   58       1           0       114         318                    0   
247   66       1           1       160         246                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  
204         0      145            0       6.2      0   3            3  
159         0      163            0       0.0      2   0            3  
219         0      150            1       0.0      2   2            3  
174         0      132            1       2.4      1   2            3  
184         0      128            0       2.6      1   0            3  
..        ...      ...          ...       ...    ...  ..          ...  
106         0      131            0       0.1      1   1            2  
105         0      115            0       1.5      1   0            2  
67          0      175            0       0.6      1   0            2  
291         2      140            0       4.4      0   3            1  
247         1      120            1       0.0      1   3            1  

[91 rows x 13 columns]

In [11]:
y_train

34     1
185    0
187    0
147    1
202    0
      ..
203    0
255    0
72     1
235    0
37     1
Name: target, Length: 212, dtype: int64

In [12]:
y_test

204    0
159    1
219    0
174    0
184    0
      ..
106    1
105    1
67     1
291    0
247    0
Name: target, Length: 91, dtype: int64

In [13]:
dt=DecisionTreeClassifier()

In [14]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
dt.score(x_train,y_train)

1.0

In [16]:
y_pred=dt.predict(x_train)

In [17]:
y_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [18]:
dt.score(x_test,y_test)

0.7032967032967034

In [19]:
y_predict=dt.predict(x_test)

In [20]:
y_predict

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1], dtype=int64)

In [22]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.66      0.71      0.68        41
           1       0.74      0.70      0.72        50

    accuracy                           0.70        91
   macro avg       0.70      0.70      0.70        91
weighted avg       0.71      0.70      0.70        91



In [23]:
dt.get_depth()

9

In [24]:
dt.get_n_leaves()

30

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rf=RandomForestClassifier()

In [28]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [29]:
rf.score(x_train,y_train)

1.0

In [30]:
y_pred1=rf.predict(x_train)

In [31]:
y_pred1

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [32]:
rf.score(x_test,y_test)

0.7362637362637363

In [33]:
y_predtest1=rf.predict(x_test)

In [34]:
y_predtest1

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0], dtype=int64)

In [35]:
print(classification_report(y_test,y_predtest1))

              precision    recall  f1-score   support

           0       0.70      0.73      0.71        41
           1       0.77      0.74      0.76        50

    accuracy                           0.74        91
   macro avg       0.73      0.74      0.73        91
weighted avg       0.74      0.74      0.74        91

