In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("bank.csv")

In [3]:
df

age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  deposit  
0        5      8      1042         1     -1         0         3        1  
1        5      8      1467         1     -1         0         3        1  
2        5      8      1389         1     -1         0         3        1  
3        5      8       579         1     -1         0         3        1  
4        5      8       673         2     -1         0         3        1  
...    ...    ...       ...       ...    ...       ...       ...      ...  
11157   20      0       257         1     -1         0         3        0  
11158   16      6        83         4     -1         0         3        0  
11159   19      1       156         2     -1         0         3        0  
11160    8      8         9         2    172         5         0        0  
11161    9      5       628         1     -1         0         3        0  

[11162 rows x 17 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [6]:
x=df.drop("deposit",axis=1)
y=df["deposit"]

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [8]:
from sklearn.svm import LinearSVC

In [9]:
linsvc=LinearSVC()

In [10]:
linsvc.fit(x_train,y_train)

LinearSVC()

In [11]:
linsvc.score(x_train,y_train)

0.6239600665557404

In [12]:
y_pred=linsvc.predict(x_train)

In [13]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [14]:
linsvc.score(x_test,y_test)

0.6270528515974918

In [15]:
y_predtest=linsvc.predict(x_test)

In [16]:
y_predtest

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [17]:
print(classification_report(y_test,y_predtest))

              precision    recall  f1-score   support

           0       0.91      0.32      0.47      1760
           1       0.56      0.97      0.71      1589

    accuracy                           0.63      3349
   macro avg       0.74      0.64      0.59      3349
weighted avg       0.75      0.63      0.59      3349



NON LINEAR SVC #1)polynomial 2)radial bias

In [18]:
#Polynomial
from sklearn.svm import SVC

In [19]:
svc=SVC(random_state=1,kernel="poly")

In [20]:
svc

SVC(kernel='poly', random_state=1)

In [21]:
svc.fit(x_train,y_train)

SVC(kernel='poly', random_state=1)

In [22]:
svc.score(x_train,y_train)

0.5801868680404454

In [23]:
y_pred1=svc.predict(x_train)

In [24]:
y_pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
y_predtest1=svc.predict(x_test)

In [26]:
y_predtest1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
svc.score(x_test,y_test)

0.5888324873096447

In [28]:
print(classification_report(y_test,y_predtest1))

              precision    recall  f1-score   support

           0       0.56      0.98      0.71      1760
           1       0.86      0.16      0.27      1589

    accuracy                           0.59      3349
   macro avg       0.71      0.57      0.49      3349
weighted avg       0.70      0.59      0.50      3349



In [29]:
svc2=SVC(random_state=1,kernel="rbf")

In [30]:
svc2.fit(x_train,y_train)

SVC(random_state=1)

In [31]:
svc2.score(x_train,y_train)

0.7382567515678996

In [32]:
y_pred2=svc2.predict(x_train)

In [33]:
y_pred2

array([1, 1, 0, ..., 0, 1, 1], dtype=int64)

In [34]:
svc2.score(x_test,y_test)

0.7414153478650344

In [35]:
y_predtest2=svc2.predict(x_test)

In [36]:
y_predtest2

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [37]:
print(classification_report(y_test,y_predtest2))

              precision    recall  f1-score   support

           0       0.72      0.84      0.77      1760
           1       0.78      0.63      0.70      1589

    accuracy                           0.74      3349
   macro avg       0.75      0.74      0.74      3349
weighted avg       0.75      0.74      0.74      3349



on this dataset decision tree random forest&boosting was giving us best prediction accuracy so svm is not suitable algorithim for this data.